content_dir: ../content
build_dir: ../build

use_navigation: true

navigation:
  de:
    - home
    - blog
  en:
    - home
    - blog

multilanguage:
  enabled: true,
  languages: [de, en]
  main: de
